### ISSUE TITLE
Fix label case sensitivity

### ISSUE THREAD

**Issue by T145** [estruyf/web-visitorbadge-nextjs#5]
Presently, the generated label is always in complete uppercase. As an example, a label set as "Visits" is rendered as "VISITS."

**Comment by estruyf** [comment]
The behavior is as follows:

- Default: uppercase
- All other styles: lowercase

In order to have more control, a new `labelStyle` property has been added with the following options: 

- `upper`: Transforms text to uppercase
- `lower`: Transforms text to lowercase
- `none`: Does not transform your text, will use the label as how you defined it.

**Comment by estruyf** [comment]
Now available on the website as well:

![new label style property](https://user-images.githubusercontent.com/2900833/177298112-266af521-8d1a-4312-9c6d-5df2bb405dd5.png)
