### ISSUE TITLE
Would be nice to know the date it starts to count and the option to show

### ISSUE THREAD

**Issue by venelouis** [estruyf/web-visitorbadge-nextjs#9]
I think: it would be nice to know the date it starts to count and the option to show,
for example:

"counting since: 01-jan-2024"

**Comment by estruyf** [comment]
Thanks, @venelouis, for the suggestion. Do you see this as a separate badge?

**Comment by venelouis** [comment]
no, in the same, as an option, like: "visitors(daily/ total /since when)"

**Comment by estruyf** [comment]
I've added this option. You can add `&dateShow=true` to the URL, and it should start showing you the date:

![image](https://github.com/estruyf/web-visitorbadge-nextjs/assets/2900833/0c085bcf-908c-42a9-a940-51f968549d9f)

If you want, you can change the `since` label by using the `&dateLabel=since` query string param.

**Comment by venelouis** [comment]
Very cool! Thanks!
